version: '3'

services:
    # The Hadatac Solr Service
    solr:
        build:
            context: ./solr
            dockerfile: Dockerfile
        container_name: hadatac_solr
        restart: always
        environment:
            SOLR_JAVA_MEM: "-Xms2g -Xmx4g"
        # Mount a volume in the mycores directory to persist data that is ingested.
        volumes:
            - hadatac-solr:/opt/solr/server
            - /data/hadatac-solr/solr-home:/opt/solr/server/solr/mycores   # Uncomment this option to use external binding
        networks:
            hadatac:
                aliases:
                    - solr
        ports:
            - "8983:8983"

    fuseki:
        build: ./fuseki
        container_name: hadatac_fuseki
        ports:
            - "3030:3030"
        networks:
            hadatac:
                aliases:
                  - fuseki
        volumes:
#            - hadatac-fuseki-data:/fuseki/databases
            - /data/hadatac-fuseki/databases:/fuseki/databases
        restart: always

    fuseki-yasgui:
        build: fuseki-yasgui
        container_name: hadatac_fuseki_yasgui
        ports:
            - "8888:8888"
        networks:
            hadatac:
                aliases:
                    - fuseki-yasgui
        environment:
            # This should be a url that points to this container
            # Proxies to the /store/sparql endpoint for fuseki
            DEFAULT_SPARQL_ENDPOINT: "http://hhear-ontlgy-dev3:3030/sparql"
        depends_on:
            -   fuseki


    # The primary hadatac web app
    hadatac:
        build: ./
        restart: always
        container_name: hadatac
        tty: true
        ports:
                - "443:443"
        networks:
            hadatac:
                aliases:
                    - hadatac
        environment:
            # Uncomment below setting when using Solr Authentication. Then rename security.json.template under solr/solr-home/ folder to security.json. Add user & passowrd detail in the hadatac.conf/hadatac-docker.conf file. All changes are mandatory for Solr Authentication to work.
            JAVA_OPTS: -Xms128m -Xmx12g -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=solr:HadatacQA -Dhttp.port=disabled -Dhttps.port=443 -Dplay.server.https.keyStore.path=/root/app/ssl/mssm/star_mssm_edu.pkcs12 -Dplay.server.https.keyStore.type=pkcs12 -Dplay.server.https.keyStore.password=password
            # JAVA_OPTS: -Xms128m -Xmx12g -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=solr:SolrRocks
            # Comment out below setting when using Solr Authentication
         #  JAVA_OPTS: -Xms128m -Xmx12g
        volumes:
            # Creates a volume to store the various csv files. This allows the data
            #   to be persisted when the container is removed or when Hadatac is rebuilt.
            # Example command: docker cp <filename> hadatac:/root/app/csvs/unprocessed_csv

            # Comment out this option to use external binding
            #            - hadatac-csvs:/root/app/csvs
            - /data/hadatac-ingestion:/data/hadatac-ingestion  # Uncomment this option to use external binding
            # Creates a volume for the config files. This way configuration file changes
            #   are persisted when the container is removed or rebuilt.

            # Comment out this option to use external binding
            #            - hadatac-conf:/root/app/conf
            - /data/conf:/hadatac/conf # Uncomment this option to use external binding
            #Comment out below if SSL certification is not required
            - /data/ssl/mssm:/root/app/ssl/mssm
        links:
            - fuseki
            - solr
        depends_on:
            - fuseki
            - solr
    shinyproxy:
        image: tetherlessworld/hadatac-shinyproxy:latest
        container_name: hadatac_shinyproxy
        ports:
            - 8081:8080
        environment:
            - "WORK_DIR=${PWD}"
        networks:
            hadatac:
                aliases:
                    - shinyproxy
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/log/hadatac_shinyproxy/server:/log"
            - "/var/log/hadatac_shinyproxy/container:/container-logs"
            - "./shinyproxy/application.yml:/opt/shinyproxy/application.yml"
            - "./shinyproxy/fragments:/opt/shinyproxy/fragments"


    dashboard-2016-34:
        image: 2016-34
        container_name: 2016-34
        build: ./shinyapps/dashboard/2016-34
        networks:
            hadatac:
                aliases:
                    - dashboard-2016-34

    dashboard-2020-0000:
        image: 2020-0000
        container_name: 2020-0000
        build: ./shinyapps/dashboard/2020-0000
        networks:
            hadatac:
                aliases:
                    - dashboard-2020-0000

    dashboard-2017-1762:
        image: 2017-1762
        container_name: 2017-1762
        build: ./shinyapps/dashboard/2017-1762
        networks:
            hadatac:
                aliases:
                    - dashboard-2017-1762

    dashboard-2016-1431:
        image: 2016-1431
        container_name: 2016-1431
        build: ./shinyapps/dashboard/2016-1431
        networks:
            hadatac:
                aliases:
                    - dashboard-2016-1431

    dashboard-2017-2121:
        image: 2017-2121
        container_name: 2017-2121
        build: ./shinyapps/dashboard/2017-2121
        networks:
            hadatac:
                aliases:
                    - dashboard-2017-2121


volumes:
    hadatac-solr:
#    hadatac-csvs:
#    hadatac-conf:

networks:
    hadatac:
