proxy:
  title: HADatAc ShinyProxy
  port: 8080
  hide-navbar: true
  template-path: ./template
  container-log-path: /container-logs
  docker:
    internal-networking: true
    container-network: "hadatac_newtwork"
  specs:
  - id: dashboard-2017-1762
    container-cmd: [ "R", "-e", "rmarkdown::run('/home/app/2017-1762/dashboard1.Rmd')" ]
    container-image: 2017-1762
    container-network: "${proxy.docker.container-network}"
  - id: dashboard-2017-2121
    container-cmd: [ "R", "-e", "rmarkdown::run('/home/app/2017-2121/dashboard2.Rmd')" ]
    container-image: 2017-2121
    container-network: "${proxy.docker.container-network}"
  - id: dashboard-2016-1431
    container-cmd: [ "R", "-e", "rmarkdown::run('/home/2016-1431/dashboard1.Rmd')" ]
    container-image: 2016-1431
    container-network: "${proxy.docker.container-network}"
logging:
  file:
    /log/shinyproxy.log

server:
  servlet:
    context-path:  /
